# Generated by Django 6.1 on 2026-08-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aiquest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=30)),
                ('class_name', models.CharField(max_length=15)),
                ('seat', models.ImageField(upload_to='')),
            ],
        ),
    ]
